server:
  port: 8080
  context-path: /boot

# Spring configuration
spring:
  application:
    name: boot
  http:
    encoding:
      charset: UTF-8
      enabled: true
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456

# Mybatis configuration
mybatis:
  type-aliases-package: com.libing.entity
  mapper-locations: classpath:mapper/*.xml
  configuration:
    use-generated-keys: true
    use-column-label: true
    map-underscore-to-camel-case: true


